stages:
  - title_check
  - release

title_check:
  stage: title_check
  script:
    - ./.githooks/bin/title_check.sh "${CI_MERGE_REQUEST_TITLE}"
  only:
    - merge_requests


release:
  image: node:19-buster-slim
  stage: release
  before_script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates python3
    - npm install -g semantic-release@21.0.7 @semantic-release/gitlab@12.0.5 @semantic-release/changelog@6.0.3 @semantic-release/exec@6.0.3 conventional-changelog-eslint@4.0.0
    - git clone ${CI_REPOSITORY_URL}
    - cd ${CI_PROJECT_NAME}
    - git checkout master
  script:
    - git status
    - semantic-release --debug
  only:
    - master
