---
- hosts: localhost
  connection: local
  vars:
    cloudstorage_traefik_version: 2.9.4
    cloudstorage_redis_version: 7.0.5
    cloudstorage_mariadb_version: 10.5.11    
  tasks:
    - include_role:
      name: ansible-role-cloudstorage
      vars:
        cloudstorage_app_version: 10.11.0
      when: cloudstorage_app == owncloud
    - include_role:
      name: ansible-role-cloudstorage
      vars:
        cloudstorage_app_version: 25.0.1
      when: cloudstorage_app == nextcloud
    

