tosca_definitions_version: tosca_simple_yaml_1_0

# Import Indigo datacloud base types
imports:
  - indigo_basic_types: https://baltig.infn.it/infn-cloud/tosca-types/raw/v2.5.1/tosca_types/base/basic_types.yaml
metadata:
  template_author: INFN-CLOUD
  template_name: docker_types
  template_version: 2.5.1


artifact_types:

  tosca.artifacts.Implementation.YAML:
    derived_from: tosca.artifacts.Implementation
    description: YAML Ansible recipe artifact
    mime_type: text/yaml
    file_ext: [ yaml, yml ]

  tosca.artifacts.AnsibleGalaxy.role:
    derived_from: tosca.artifacts.Root
    description: Ansible Galaxy role to be deployed in the target node


node_types:

  tosca.nodes.indigo.dockerRun:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      role_name:
        type: string
        required: no
        default: indigo-dc.docker_run
      docker_appname:
        type: string
        required: no
        default: ubuntu
      docker_image:
        type: string
        required: no
        default: ubuntu
      docker_tag:
        type: string
        required: no
        default: latest
      docker_ports:
        type: list
        entry_schema:
          type: string   
        required: no
        default: [] 
      docker_command:
        type: string
        required: no
        default: ""
      environment_variables:
        required: no
        default: []
        type: list
        entry_schema:
          type: map
          entry_schema:
            type: string
    artifacts:
      docker_role:
        file: indigo-dc.docker,v2.1.2
        type: tosca.artifacts.AnsibleGalaxy.role
      dockerrun_role:
        file: indigo-dc.docker_run,v1.0.1
        type: tosca.artifacts.AnsibleGalaxy.role
    interfaces:
      Standard:
        start:
          implementation: https://baltig.infn.it/infn-cloud/tosca-types/raw/v2.5.1/artifacts/dodas/ansible.yaml
          inputs:
            role_name:  { get_property: [ SELF, role_name ] }
            docker_run_appname: { get_property: [ SELF, docker_appname ] }
            docker_run_image: { get_property: [ SELF, docker_image ] }
            docker_run_tag: { get_property: [ SELF, docker_tag ] }
            docker_run_ports: { get_property: [ SELF, docker_ports ] }
            docker_run_command: { get_property: [ SELF, docker_command ] }
            docker_run_env_variables: { get_property: [ SELF, environment_variables ] }


  tosca.nodes.indigo.DockerCompose:
    derived_from: tosca.nodes.SoftwareComponent
    properties:
      docker_compose_version:
        type: version
        required: no
        default: 1.29.2
      docker_compose_file_url:
        type: string
        required: no
        default: ""
      environment_variables:
        required: no
        default: []
        type: list
        entry_schema:
          type: map
          entry_schema:
            type: string
      project_name:
        type: string
        required: yes
    artifacts:
      docker_role:
        file: indigo-dc.docker,v2.1.3
        type: tosca.artifacts.AnsibleGalaxy.role
    interfaces:
      Standard:
        start:
          implementation: https://baltig.infn.it/infn-cloud/tosca-types/raw/v2.5.1/artifacts/docker/docker-compose_start.yml
          inputs:
            docker_compose_version: { get_property: [ SELF, docker_compose_version ] }
            docker_compose_file_url:  { get_property: [ SELF, docker_compose_file_url ] }
            project_name:  { get_property: [ SELF, project_name ] }
            environment_variables: { get_property: [ SELF, environment_variables ] }

