---
- hosts: localhost
  connection: local

  vars:
    master_host: vnode-0

  pre_tasks:
    - name: Get hostname
      shell: hostname
      register: hostname

    - name: Check if master_host is in hostname
      set_fact:
        is_master_host: "{{ master_host in hostname.stdout }}"

    - name: Install collection ansible.posix
      become: yes
      community.general.ansible_galaxy_install:
        type: collection
        name: ansible.posix
      when: is_master_host

  roles:
    - role: "{{ role_name }}"
