---
- hosts: localhost
  connection: local
  vars:
    master_host: vnode-0
  tasks:

    - name: Get hostname
      shell: hostname
      register: hostname

    - name: Check if master_host is in hostname
      set_fact:
        is_master_host: "{{ master_host in hostname.stdout }}"

    - name: Ansible POSIX mount module installation
      become: yes
      shell: "ansible-galaxy collection install ansible.posix"
      when: is_master_host
