---
- hosts: localhost
  connection: local
  roles:
    - role: indigo-dc.openvpn
      openvpn_type_of_node: "wn"
      openvpn_frontname: "kubeserver"
      when: wn_hybrid_cluster
    - role: ansible-role-kubernetes
      #role: dodas.kubernetes
      kube_type_of_node: "wn"
      kube_server: "{{ kube_front_end_ip }}"
      kube_api_server: "{{ kube_front_end_ip }}"
      # Properties related to GPU support:
      # gpu_support_role: git+https://baltig.infn.it/infn-cloud/ansible-role-gpu-support,v1.0.0
      # nvidia_driver_role: nvidia.nvidia_driver
      # nvidia_driver_branch: "515"
      # nvidia_driver_ubuntu_install_from_cuda_repo: true
      # nvidia_driver_skip_reboot: true
