---
- hosts: localhost
  connection: local
  tasks:
    - name: set timezone to Europe/Rome
      timezone:
        name: Europe/Rome

    - name: "create directory path to store the configuration files"
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      loop:
        - "/opt/{{ project_name }}"
        - "/opt/{{ project_name }}/traefik"

    - name: download tls.toml
      get_url:
        url:  "https://baltig.infn.it/infn-cloud/tosca-types/raw/master/artifacts/docker/cloudstorage/tls.toml"
        dest: "/opt/{{ project_name }}/traefik/tls.toml"
        mode: 0440

    - name: debug
      debug: 
        var: environment_variables

    - name: Set environment variables
      lineinfile:
        path: /opt/{{ project_name }}/.env
        line: "{{ item.key }}={{ item.value }}"
        create: yes
      with_dict: "{{ environment_variables }}"

    - name: Add HOST_PUBLIC_IP and additional environment variables
      lineinfile:
        path: /opt/{{ project_name }}/.env
        line: "{{ item.key }}={{ item.value }}"
        create: yes
      with_items:
         - { key: "TRAEFIK_VERSION", value: "{{ traefik_version | replace(\"'\",\"\") }}" }
         - { key: "OWNCLOUD_VERSION", value: "{{ owncloud_version | replace(\"'\",\"\") }}" }
         - { key: "OWNCLOUD_HOSTNAME", value: "{{ owncloud_hostname }}" }
         - { key: "NAGIOS_HOSTNAME", value: "{{ nagios_hostname }}" }
         - { key: "DUPLICATI_HOSTNAME", value: "{{ duplicati_hostname }}" }
         - { key: "HOST_PUBLIC_IP", value: "{{ IM_NODE_PUBLIC_IP }}" }
         - { key: "S3_ENDPOINT", value: "{{ s3_endpoint }}" }
         - { key: "S3_SECRET_KEY", value: "{{ s3_secret_key }}" }
         - { key: "S3_ACCESS_KEY", value: "{{ s3_access_key }}" }
         - { key: "S3_BUCKET", value: "{{ s3_bucket }}" }
